iniciarSesiN = "(//span[contains(.,'Iniciar sesión')])[1]"
userName = "//input[contains(@id,'username')]"
password0 = "//input[contains(@id,'password')]"
BotonLogin = "//button[@name='login']"
Busqueda = "(//input[@type='search'])[1]"
SeleccionProducto = "(//a[contains(.,'Alikal')])[1]"
TituloValidate="//h1[@class='product-title product_title entry-title']"
DescripcionValidate = "//a[@href='#tab-description']"
ValorConfirmed = "//input[contains(@value,'+')]"
agregarAlCarrito = "//button[@name='add-to-cart']"
carrito = "//span[contains(@class,'header-cart-title')]"
confirmarReserva = "//a[contains(.,'Confirmar reserva')]"
NombreReserva = "//input[@id='billing_first_name']"
ApellidoReserva = "//input[@id='billing_last_name']"
CelReserva = "//input[contains(@id,'phone')]"
ComentarioReserva = "//textarea[@id='order_comments']"
finalizarLaReserva = "//button[@id='place_order']"
nMeroDelPedido = "//li[contains(@class,'order order')]"
